# Generated by Django 4.1.3 on 2022-11-25 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_complete']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='complete',
            new_name='is_complete',
        ),
    ]
